---
- name: Test File Transfer from Local Server
  hosts: all
  become: true
  vars:
  
  tasks:
  - name: Copy SSSD Config to /etc/sssd
    copy:
      remote_src: yes
      src: testfile.test
      dest: /tmp/testfile.test
