---
- name: Test File Transfer from Local Server
  hosts: all
  become: true
  vars:
  
  tasks:
  - name: Copy SSSD Config to /etc/sssd
    copy:
      src: omsagent-1.14.12-0.universal.x64.sh
      dest: /tmp/omsagent-1.14.12-0.universal.x64.sh
