---
- name: Test File Transfer from Local Server
  hosts: all
  become: true
  vars:
  
  tasks:
  - name: Copy SSSD Config to /etc/sssd
    expect:
      command: /bin/bash -c 'scp "ansible@cis.ccsd.net"@172.16.192.69:/AnsibleFS/testfile /tmp/'
      responses:
        - (?i)The: "yes"
