---
- name: Test File Transfer from Local Server
  hosts: all
  become: true
  vars:
  
  tasks:
  - name: Copy SSSD Config to /etc/sssd
    copy:
      src: /AnsibleFS/sssd.conf
      dest: /tmp/sssd.conf
